import { ChallengeTemplate } from '@domain/entities/challenge-template.entity';

export const CHALLENGE_TEMPLATE_SEEDS: ChallengeTemplate[] = [
  // Category 1: time_goal
  ChallengeTemplate.create({
    id: 'time-under-40',
    category: 'time_goal',
    name: '40분 이내 출근 3회',
    description: '이번 주 안에 40분 이내로 출근하는 걸 3번 달성해보세요!',
    targetValue: 3,
    conditionType: 'duration_under',
    conditionValue: 40,
    durationDays: 7,
    badgeId: 'lightning',
    badgeName: '번개',
    badgeEmoji: '⚡',
    difficulty: 'easy',
    sortOrder: 1,
  }),
  ChallengeTemplate.create({
    id: 'time-under-30',
    category: 'time_goal',
    name: '30분 이내 출근 5회',
    description: '2주 안에 30분 이내로 출근하는 걸 5번 달성해보세요!',
    targetValue: 5,
    conditionType: 'duration_under',
    conditionValue: 30,
    durationDays: 14,
    badgeId: 'rocket',
    badgeName: '로켓',
    badgeEmoji: '🚀',
    difficulty: 'hard',
    sortOrder: 2,
  }),
  // Category 2: streak
  ChallengeTemplate.create({
    id: 'streak-3d',
    category: 'streak',
    name: '3일 연속 출퇴근',
    description: '이번 주 안에 3일 연속으로 출퇴근을 기록해보세요!',
    targetValue: 3,
    conditionType: 'consecutive_days',
    conditionValue: 3,
    durationDays: 7,
    badgeId: 'fire',
    badgeName: '불꽃',
    badgeEmoji: '🔥',
    difficulty: 'easy',
    sortOrder: 3,
  }),
  ChallengeTemplate.create({
    id: 'streak-5d',
    category: 'streak',
    name: '5일 연속 출퇴근',
    description: '이번 주 안에 평일 5일 연속 출퇴근을 달성해보세요!',
    targetValue: 5,
    conditionType: 'consecutive_days',
    conditionValue: 5,
    durationDays: 7,
    badgeId: 'crown',
    badgeName: '왕관',
    badgeEmoji: '👑',
    difficulty: 'hard',
    sortOrder: 4,
  }),
  // Category 3: weekly_frequency
  ChallengeTemplate.create({
    id: 'weekly-4',
    category: 'weekly_frequency',
    name: '이번 주 4일 출퇴근',
    description: '이번 주 안에 4일 이상 출퇴근을 기록해보세요!',
    targetValue: 4,
    conditionType: 'weekly_count',
    conditionValue: 4,
    durationDays: 7,
    badgeId: 'calendar',
    badgeName: '달력',
    badgeEmoji: '📅',
    difficulty: 'medium',
    sortOrder: 5,
  }),
  ChallengeTemplate.create({
    id: 'weekly-perfect',
    category: 'weekly_frequency',
    name: '완벽한 한 주',
    description: '월요일부터 금요일까지 매일 출퇴근을 기록해보세요!',
    targetValue: 5,
    conditionType: 'weekday_complete',
    conditionValue: 5,
    durationDays: 7,
    badgeId: 'star',
    badgeName: '별',
    badgeEmoji: '⭐',
    difficulty: 'hard',
    sortOrder: 6,
  }),
];
